routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::auth();
Auth::routes();

Route::any('/search', 'NuanceController@search');

Route::resource('user', 'UserController');

Route::resource('chute', 'ChuteController');
Route::resource('nuance', 'NuanceController');
Route::get('nuance/designation/{designation}', 'NuanceController@indexDesignation');
// Route::resource('designation', 'DesignationController');
Route::resource('commande', 'CommandeController');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'email', 'password','gender', 'lastName', 'firstName',
        'company', 'siret',
        'addressLine1', 'addressLine2', 'postCode', 'city', 'country',
        'tel', 'fax',
        'pay', 'fidel',
        'admin',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\UserCreateRequest;
use App\Http\Requests\UserUpdateRequest;

use App\Repositories\UserRepository;

class UserController extends Controller
{
  protected $userRepository;
  protected $nbrPerPage = 5;

  public function __construct(UserRepository $userRepository)
  {
    $this->userRepository = $userRepository;
  }
  // what you see on qualichutes/user, index of all user, admin interface
  public function index()
  {
    $users = $this->userRepository->getPaginate($this->nbrPerPage);
    $links = $users->render();

    return view('users.index', compact('users', 'links'));
  }
  // load create form, used in register
  public function create()
  {
    return view('users.create');
  }
  // insert new user, from create form
  public function store(UserCreateRequest $request)
  {
    $this->setAdmin($request);

    $user = $this->userRepository->store($request->all());
    return redirect('user')->withOk("L'utilisateur " . $request->email . " a été créé.");
  }
  // load a specific page for an user
  public function show($id)
  {
    $user = $this->userRepository->getById($id);

    return view('users.show',  compact('user'));
  }
  // load edit form
  public function edit($id)
  {
    $user = $this->userRepository->getById($id);

    return view('users.edit',  compact('user'));
  }
  // update an existing user, from edit form
  public function update(UserUpdateRequest $request, $id)
  {
    $this->setAdmin($request);

    $this->userRepository->update($id, $request->all());

    return redirect('user')->withOk("L'utilisateur a été modifié.");
  }
  // delete a nuance
  public function destroy($id)
  {
    $this->userRepository->destroy($id);

    return back();
  }
  // by default admin set to FALSE
  private function setAdmin($request)
  {
    if(!$request->has('admin'))
    {
      $request->merge(['admin' => 0]);
    }
  }
}

resources/views/users/create.blade.php
@extends('templateUserForm')

@section('title')
  Create user
@endsection

@section('card-header')
  <div class="card-header bg-lightGrey">{{__('Create') }}
  </div>
@endsection

@section('form-open')
  <form method="POST" action="{{ route('user.store') }}">
@endsection

@section('submit')
  <button type="submit" class="btn bg-lightGreen float-right"> {{ __('Create') }} </button>
@endsection

resources/views/users/edit.blade.php
@extends('template')

@section('title')
  Edit user
@endsection

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header"> Edit user
          </div>
          {{-- open form --}}
          {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'put']) !!}
          {{-- email --}}
          <div class="form-group row">
            {!! Form::label('email', 'e-mail address', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::email('email', null, ['class' => 'form-control', 'placeholder' => $user->email]) !!}
              {!! $errors->first('email', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- gender --}}
          <div class="form-group row">
            {!! Form::label('gender', 'Gender', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::radio('gender', 'Mr') !!} Mr
              {!! Form::radio('gender', 'Mme') !!} Mme
              {!! Form::radio('gender', 'NC') !!} NC
            </div>
          </div>
          {{-- lastName --}}
          <div class="form-group row">
            {!! Form::label('lastName', 'Nom', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('lastName', null, ['class' => 'form-control', 'placeholder' => $user->lastName]) !!}
              {!! $errors->first('lastName', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- firstName --}}
          <div class="form-group row">
            {!! Form::label('firstName', 'Prénom', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('firstName', null, ['class' => 'form-control', 'placeholder' => $user->firstName]) !!}
              {!! $errors->first('firstName', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- company --}}
          <div class="form-group row">
            {!! Form::label('company', 'Société', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('company', null, ['class' => 'form-control', 'placeholder' => $user->company]) !!}
              {!! $errors->first('company', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- SIRET --}}
          <div class="form-group row">
            {!! Form::label('siret', 'SIRET', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('siret', null, ['class' => 'form-control', 'placeholder' => $user->siret]) !!}
              {!! $errors->first('siret', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- addressLine1 --}}
          <div class="form-group row">
            {!! Form::label('addressLine1', 'Address', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('addressLine1', null, ['class' => 'form-control', 'placeholder' => $user->addressLine1]) !!}
              {!! $errors->first('addressLine1', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- addressLine2 --}}
          <div class="form-group row">
            {!! Form::label('addressLine2', 'Address suite', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('addressLine2', null, ['class' => 'form-control', 'placeholder' => $user->addressLine2]) !!}
              {!! $errors->first('addressLine2', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- postCode --}}
          <div class="form-group row">
            {!! Form::label('postCode', 'Postal Code', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('postCode', null, ['class' => 'form-control', 'placeholder' => $user->postCode]) !!}
              {!! $errors->first('postCode', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- City --}}
          <div class="form-group row">
            {!! Form::label('city', 'City', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('city', null, ['class' => 'form-control', 'placeholder' => $user->city]) !!}
              {!! $errors->first('city', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- Country --}}
          <div class="form-group row">
            {!! Form::label('country', 'Country', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('country', null, ['class' => 'form-control', 'placeholder' => $user->country]) !!}
              {!! $errors->first('country', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- phone --}}
          <div class="form-group row">
            {!! Form::label('tel', 'Téléphone', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('tel', null, ['class' => 'form-control', 'placeholder' => $user->tel]) !!}
              {!! $errors->first('tel', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- fax --}}
          <div class="form-group row">
            {!! Form::label('fax', 'Fax', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::text('fax', null, ['class' => 'form-control', 'placeholder' => $user->fax]) !!}
              {!! $errors->first('fax', '<small class="help-block">:message</small>') !!}
            </div>
          </div>
          {{-- pay --}}
          <div class="form-group row">
            {!! Form::label('pay', 'Payement mode', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
            <div class="col-md-6">
              {!! Form::radio('pay', 'LCR') !!}       LCR
              {!! Form::radio('pay', 'virement') !!}  virement
              {!! Form::radio('pay', 'paypal') !!}    paypal
              {!! Form::radio('pay', 'chèque') !!}    chèque
            </div>
          </div>
          {{-- fidelity --}}
            <div class="form-group row">
              {!! Form::label('fidel', 'fidelity status', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
              <div class="col-md-6">
                {!! Form::radio('fidel', 'newcomer') !!}  Newcomer
                {!! Form::radio('fidel', 'gold') !!}      Gold
                {!! Form::radio('fidel', 'platinium') !!} Platinium
              </div>
            </div>
          {{-- admin --}}
          <div class="form-group">
            <div class="checkbox">
              <label>
                {!! Form::checkbox('admin', 1, null) !!}Administrateur
              </label>
            </div>
          </div>
          {!! Form::submit('Envoyer', ['class' => 'btn btn-primary float-right']) !!}
          {!! Form::close() !!}
        </div>
      </div>
    </div>
    <a href="javascript:history.back()" class="btn bg-lightGrey"> <span class="fa fa-arrow-circle-left"> </span> Retour </a>
  </div>


@endsection

resources/views/users/index.blade.php
@extends('template')

@section('title')
  Users index
@endsection

@section('content')
  <div class="col-sm-8">
    @if(session()->has('ok'))
      <div class="alert alert-success alert-dismissible">{!! session('ok') !!}</div>
    @endif
    <div class="card">
      <div class="card-header bg-lightGrey">
        <h3>Liste des utilisateurs</h3>
      </div>
      <table class="table table-dark table-striped">
        <thead>
          <tr>
            <th class="col-sm-2">#</th>
            <th class="col-sm-6">email</th>
            <th class="col-sm-2"></th>
            <th class="col-sm-2"></th>
            <th class="col-sm-2"></th>
          </tr>
        </thead>
        <tbody>
          @foreach ($users as $user)
            <tr>
              <td>{!! $user->id !!}</td>
              <td class="text-primary"><strong>{!! $user->email !!}</strong></td>
              <td>{!! link_to_route('user.show', 'Voir', [$user->id], ['class' => 'btn bg-green btn-block']) !!}</td>
              <td>{!! link_to_route('user.edit', 'Modifier', [$user->id], ['class' => 'btn bg-yellow btn-block']) !!}</td>
              <td>
                {!! Form::open(['method' => 'DELETE', 'route' => ['user.destroy', $user->id]]) !!}
                {!! Form::submit('Supprimer', ['class' => 'btn bg-red btn-block', 'onclick' => 'return confirm(\'Vraiment supprimer cet utilisateur ?\')']) !!}
                {!! Form::close() !!}
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
    {!! link_to_route('user.create', 'Ajouter un utilisateur', [], ['class' => 'btn bg-lightBlue float-right']) !!}
    {!! $links !!}
  </div>
@endsection

resources/views/users/show.blade.php
@extends('template')

@section('title')
  Show user
@endsection

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header"> Fiche utilisateur
          </div>
          <p>Email :            {{ $user->email }}</p>
          <p>Gender :           {{ $user->gender }}</p>
          <p>Last Name :        {{ $user->lastName }}</p>
          <p>First Name :       {{ $user->firstName }}</p>
          <p>Company :          {{ $user->company }}</p>
          <p>SIRET :            {{ $user->siret }}</p>
          <p>Address :          {{ $user->addressLine1 }}</p>
          <p>Addres suite :     {{ $user->addressLine2 }}</p>
          <p>Postal Code :      {{ $user->postCode }}</p>
          <p>City :             {{ $user->city }}</p>
          <p>Country :          {{ $user->country }}</p>
          <p>Phone :            {{ $user->tel }}</p>
          <p>Fax :              {{ $user->fax }}</p>
          <p>Payment mode :     {{ $user->pay }}</p>
          <p>Fidelity status :  {{ $user->fidel }}</p>
          @if($user->admin == 1)
            Administrateur
          @endif
        </div>
      </div>
    </div>
  </div>
  <a href="javascript:history.back()" class="btn btn-primary float-left"> <span class="fa fa-arrow-circle-left"> </span> Retour </a>
@endsection