routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::auth();
Auth::routes();

Route::any('/search', 'NuanceController@search');

Route::resource('user', 'UserController');

Route::resource('chute', 'ChuteController');
Route::resource('nuance', 'NuanceController');
Route::get('nuance/designation/{designation}', 'NuanceController@indexDesignation');
// Route::resource('designation', 'DesignationController');
Route::resource('commande', 'CommandeController');

app/Models/Nuance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Nuance extends Model
{

    protected $fillable = [
        'famille', 'nuanceName', 'densite', 'designationNorme', 'designationName'
    ];

    public function designations()
    {
      return $this->hasMany('App\Models\Designation');
    }

    public function chutes()
    {
      return $this->hasMany('App\Models\Chute');
    }

}

app/Http/Controllers/NuanceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests\NuanceCreateRequest;
use App\Http\Requests\NuanceUpdateRequest;

use App\Repositories\NuanceRepository;

use App\Models\Nuance;
use App\Models\Designation;

class NuanceController extends Controller
{
  protected $nuanceRepository;
  protected $nbrPerPage = 12;

  public function __construct(NuanceRepository $nuanceRepository)
  {
    // seul un administrateur peut créer, éditer ou détruire une nuance
    $this->middleware('admin', ['only' => 'create', 'edit', 'destroy']);
    $this->nuanceRepository = $nuanceRepository;
  }

  // catalogue de nuance
  public function index()
  {
    $nuances = $this->nuanceRepository->getWithDesignationAndPaginate($this->nbrPerPage);
    // translate nuance->famille from DB to user eyes
    foreach ($nuances as $nuance) {
      switch($nuance->famille) {
        case 'acConstrAllie' :
        $family = 'Aciers de Constructions et Alliés';
        break;
        case 'acInox' :
        $family = 'Aciers Inoxydables';
        break;
        case 'acOutils' :
        $family = 'Aciers Outils';
        break;
        case 'plastTech' :
        $family = 'Plastiques Techniques';
        break;
        case 'alu' :
        $family = 'Aluminiums';
        break;
        case 'cuivre'  :
        $family = 'Cuivreux';
        break;
        case 'bronze'  :
        $family = 'Bronze';
        break;
        case 'acEtire'  :
        $family = 'Aciers Étirés';
        break;
        case 'tubeMeca'  :
        $family = 'Tubes Mécaniques';
        break;
        case 'tigeChrome'  :
        $family = 'Tiges Chromées';
        break;
        case 'fonte' :
        $family = 'Fontes';
        break;
        case 'toleBleue' :
        $family = 'Tôles Bleues';
        break;
        case 'megaStubs' :
        $family = 'MégaStubs';
        break;
        case 'acRessort'  :
        $family = 'Aciers à Ressort';
        break;
      }
      $nuance->famille = $family;
    }
    $links = $nuances->render();
    return view('nuances.nuances', compact('nuances', 'links'));
  }

  // load create form
  public function create()
  {
    return view('nuances.nuancesAdd');
  }

  // insert new nuance, from create form with one designationNorme->designationName
  public function store(NuanceCreateRequest $request)
  {
    // $data = Nuance::create([
    //   'famille' => $request->famille, 'nuanceName' => $request->nuanceName, 'densite' => $request->densite,
    // ]);
    // Designation::insert([
    //   'nuance_id' => $data->id, 'designationNorme' => $request->designationNorme, 'designationName' => $request->designationName,
    // ]);
    print_r($request->all());

    $famille = $request->famille;
    $nuanceName = $request->nuanceName;
    $densite = $request->densite;
    $data = Nuance::create([
      'famille' => $famille, 'nuanceName' => $nuanceName, 'densite' => $densite,
    ]);

    $nuance_id = $data->id;
    $designationNorme = $request['designationNorme'];
    $designationName = $request['designationName'];
    for($i=0;$i<count($designationName);$i++)
    {
      Designation::create([
        'nuance_id' => $nuance_id, 'designationNorme' => $designationNorme[$i], 'designationName' => $designationName[$i]]);
      // "insert into designations values('$name[$i]','$age[$i]','$job[$i]')");
    }

    return redirect('nuance')->withOk("La nuance" . $request->nuanceName . "a été créée");
  }

  // load a specific page for a nuance
  public function show($id)
  {
    $nuance = $this->nuanceRepository->getByIdWithDesignation($id);
    return view('nuances.nuancesShow', compact('nuance'));
  }

  // load edit form
  public function edit($id)
  {
    $nuance = $this->nuanceRepository->getById($id);
    return view('nuances.nuancesEdit', compact('nuance'));
  }

  // update an existing nuance, from edit form
  public function update(NuanceUpdateRequest $request, $id)
  {
    /*//////////////////////////////////
    // supposed to edit designations
    if(isset($inputs['designations']))
    {
    $designationRepository->store($nuance, $inputs['designations']);
  }
  $this->nuanceRepository->update($id, $request->all());
  ///////////////////////////////////////////////////////*/
  $nuance = $this->nuanceRepository->update($id, [
    'famille' => $request->famille, 'nuanceName' => $request->nuanceName, 'densite' => $request->densite,
  ]);
  Designation::updateOrCreate([
    'nuance_id' => $id, 'designationNorme' => $request->designationNorme, 'designationName' => $request->designationName,
  ]);
  return redirect('nuance');
}

// delete a nuance
public function destroy($id)
{
  $nuance = $this->nuanceRepository->getById($id);
  $nuance->designations()->delete();
  $this->nuanceRepository->destroy($id);
  return back();
}

// prepare search by designation
public function indexDesignation($designation)
{
  $nuances = $this->nuanceRepository->getWithDesignationForSearch($designation, $this->nbrPerPage);
  $links = $nuances->render();
  return view('nuances.nuances', compact('nuances', 'links'))->with('info', 'Résultats pour la recherche :' .$designation);
}

public function search(Request $request)
{
  $q = $request->input('q');
  $nuance = $this->nuanceRepository->getWithDesignationForSearch($q, $this->nbrPerPage);
  if(count($nuance) > 0)
  {
    return view('nuances.nuancesSearch')->withDetails($nuance)->withQuery($q);
  } else {
    return view('nuances.nuancesSearch')->withMessage('No nuances found. Try to search again!');
  }
}

}

?>

resources/views/nuances/nuances.blade.php
@extends('template')

@section('title')
  Nuances
@endsection

@section('content')
  @if(Auth::check() and Auth::user()->admin)
    {!! link_to_route('nuance.create', 'Ajouter une nuance', [], ['class' => 'btn bg-lightGreen float-right']) !!}
  @endauth
  @if(isset($info))
    <div class="row alert alert-info"> {{ $info }} </div>
  @endif
  <div class="mt-3 ml-5">
    {!! $links !!}
  </div>

  <div class="row">
    @foreach ($nuances as $nuance)
      <div class="card col-sm-3">
        <div class="card-header bg-lightGrey">
          <a href="nuance/{{$nuance->id}}"> {{ $nuance->nuanceName }} </a>
          <span class="float-right"> {{$nuance->famille}} </span>
        </div>
        <div class="card-body">
          <table>
            @foreach ($nuance->designations as $designation)
              <tr>
                <td class="col-sm-4">{{ $designation->designationNorme }}</td>
                <td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
                <td class="col-sm-4">{{ $designation->designationName }}</td>
              </tr>
            @endforeach
          </table>
        </div>
        @if(Auth::check() and Auth::user()->admin)
          <div class="card-footer">
            <a href="nuance/{{ $nuance->id }}/edit" class="float-left"> Éditer la nuance </a>
            {!! Form::open(['method' => 'DELETE', 'route' => ['nuance.destroy', $nuance->id]]) !!}
            {!! Form::submit('Supprimer cette nuance', ['class' => 'btn btn-danger float-right', 'onclick' => 'return confirm(\'Voulez-vous vraiment supprimer cette nuance ?\')']) !!}
            {!! Form::close() !!}
          </div>
        @endif
      </div>
    @endforeach
  </div>
  {!! $links !!}
@endsection

resources/views/nuances/nuancesAdd.blade.php
@extends('template')

@section('content')
	<div class="container">
		<div class="card col-md-10">
			<div class="card-header bg-lightGrey">
				Ajouter une nuance
			</div>
			<div class="card-body">
				{!! Form::open(array('route' => 'nuance.store', 'method' => 'POST')) !!}
				{{-- famille --}}
				<div class="form-group row">
					{!! Form::label('famille', 'Famille:', ['class' => 'col-md-3 col-form-label text-md-right']) !!}
					<div class="col-md-9">
						{!! Form::radio('famille', 'acConstrAllie') !!}	Aciers de Construction et Alliés	<br>
						{!! Form::radio('famille', 'acInox') !!}				Aciers Inoxydables								<br>
						{!! Form::radio('famille', 'acoutils') !!}			Aciers Outils											<br>
						{!! Form::radio('famille', 'plastTech') !!}			Plastiques techniques							<br>
						{!! Form::radio('famille', 'alu') !!}						Aluminiums												<br>
						{!! Form::radio('famille', 'cuivre') !!}				Cuivreux													<br>
						{!! Form::radio('famille', 'bronze') !!}				Bronzes														<br>
						{!! Form::radio('famille', 'acEtire') !!}				Aciers Outils											<br>
						{!! Form::radio('famille', 'tubeMeca') !!}			Tubes Mécaniques									<br>
						{!! Form::radio('famille', 'toleBleue') !!}			Tôles Bleues											<br>
						{!! Form::radio('famille', 'tigeChrome') !!}		Tiges Chromées										<br>
						{!! Form::radio('famille', 'fonte') !!}					Fontes														<br>
						{!! Form::radio('famille', 'acRessort') !!}			Aciers à Ressort									<br>
					</div>
				</div>
				{{-- name --}}
				<div class="form-group row">
					{!! Form::label('nuanceName', 'Name:', ['class' => 'col-md-3 col-form-label text-md-right']) !!}
					<div class="col-md-9">
						{!! Form::text('nuanceName', null, ['placeholder' => 'nom']) !!}
					</div>
				</div>
				{{-- désignations --}}
				<div class="form-group row">
					{!! Form::label('designations', 'Désignations:', ['class' => 'col-md-3 col-form-label text-md-right']) !!}
					<ul id="designation_table" class="col-md-9" style="list-style-type:none;">
						<li id="row1">
								{!! Form::text('designationNorme[]', null, ['placeholder' => 'norme', 'class' => 'col-md-3']) !!}
								{!! Form::text('designationName[]', null, ['placeholder' => 'name', 'class' => 'col-md-3']) !!}
						</li>
						<input type="button" onclick="add_row();" value="Add Row" class="btn bg-lightBlue float-left">
					</ul>

				</div>
				{{-- densite --}}
				<div class="form-group row">
					{!! Form::label('densite', 'Densite:', ['class' => 'col-md-3 col-form-label text-md-right']) !!}
					<div class="col-md-9">
						{!! Form::text('densite') !!}
					</div>
				</div>
				{!! Form::submit('Ajouter', ['class' => 'btn bg-lightGreen float-right']) !!}
				{!! Form::close() !!}
				<a href="javascript:history.back()" class="btn bg-lightGrey float-left"> <span class="fa fa-arrow-circle-left"> </span> Retour </a>
			</div>
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
function add_row()
{
	$rowno=$("#designation_table li").length;
	$rowno=$rowno+1;
	$("#designation_table li:last").after("<li id='row"+$rowno+"'><input type='text' name='designationNorme[]' placeholder='norme' class='col-md-3'> <input type='text' name='designationName[]' placeholder='name' class='col-md-3'> <input type='button' value='Delete' class='bg-lightGrey col-md-3' onclick=delete_row('row"+$rowno+"')></li>");
}
function delete_row(rowno)
{
	$('#'+rowno).remove();
}
</script>

@endsection

resources/views/nuances/nuancesEdit.blade.php
@extends('template')

@section('content')
	<div class="container">
		<div class="row jutify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						Éditer la nuance {{ $nuance->nuanceName }}
					</div>
					<div class="card-body">
						{!! Form::model($nuance, ['route' => ['nuance.update', $nuance->id] , 'method' => 'PUT']) !!}
						{{-- famille --}}
						<div class="form-group row">
							{!! Form::label('famille', 'famille', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
							<div class="col-md-6">
								<input type="radio" name="famille"  value="acConstrAllie"	{{ $nuance->famille == 'acConstrAllie' ? 'checked' : '' }} >	Aciers de Construction et Alliés <br>
								<input type="radio" name="famille"  value="acInox"				{{ $nuance->famille == 'acInox' ? 'checked' : '' }} >					Aciers Inoxydables <br>
								<input type="radio" name="famille"  value="acOutils"			{{ $nuance->famille == 'acOutils' ? 'checked' : '' }} >				Aciers Outils <br>
								<input type="radio" name="famille"  value="plastTech"			{{ $nuance->famille == 'plastTech' ? 'checked' : '' }} >			Plastiques Techniques <br>
								<input type="radio" name="famille"  value="alu"						{{ $nuance->famille == 'alu' ? 'checked' : '' }} >						Aluminiums <br>
								<input type="radio" name="famille"  value="cuivre"				{{ $nuance->famille == 'cuivre' ? 'checked' : '' }} >					Cuivreux <br>
								<input type="radio" name="famille"  value="bronze"				{{ $nuance->famille == 'bronze' ? 'checked' : '' }} >					Bronzes <br>
								<input type="radio" name="famille"  value="acEtire"				{{ $nuance->famille == 'acEtire' ? 'checked' : '' }} >				Aciers Étirés <br>
								<input type="radio" name="famille"  value="tubeMeca"			{{ $nuance->famille == 'tubeMeca' ? 'checked' : '' }} >				Tubes Mécaniques <br>
								<input type="radio" name="famille"  value="tigeChrome"		{{ $nuance->famille == 'tigeChrome' ? 'checked' : '' }} >			Tiges Chromées <br>
								<input type="radio" name="famille"  value="fonte"					{{ $nuance->famille == 'fonte' ? 'checked' : '' }} >					Fontes <br>
								<input type="radio" name="famille"  value="acRessort"			{{ $nuance->famille == 'acRessort' ? 'checked' : '' }} >			Aciers à Ressort <br>
								<br>
							</div>
						</div>
						{{-- name --}}
						<div class="form-group row">
							{!! Form::label('nuanceName', 'Name:', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
							<div class="col-md6-">
								{!! Form::text('nuanceName', null, ['placeholder' => 'nuanceName']) !!}
							</div>
						</div>
						{{-- designations --}}
						<div class="form-group row">
							{!! Form::label('designations', 'Désignations:', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
							@foreach ($nuance->designations as $designation)
								<div class="col-md6-">
									{!! Form::text('designationNorme', $designation->designationNorme) !!}
									{!! Form::text('designationName', $designation->designationName) !!}
								</div>
							@endforeach
						</div>
						{{-- densite --}}
						<div class="form-group row">
							{!! Form::label('densite', 'Densite:', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
							<div class="col-md-6">
								{!! Form::text('densite', null, ['placeholder' =>'densite']) !!}
							</div>
						</div>
						{!! Form::submit('Éditer', ['class' => 'btn bg-green float-right']) !!}
						{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
	<a href="javascript:history.back()" class="btn bg-lightGrey"> <span class="fa fa-arrow-circle-left"> </span> Retour </a>
@endsection

resources/views/nuances/nuancesSearch.blade.php
@extends('template')

@section('title')
  Search results
@endsection

@section('content')
  <div class="container">
    @if (isset($details))
      <p> The search results for your query {{ $query}} are : </p>
      <h2>Nuance search</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Normes <span class="fa fa-arrow-circle-right" aria-hidden="true"></span> Designations</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($details as $nuance)
            <tr>
              <td>{{$nuance->name}}</td>
              <td>
                @foreach ($nuance->designations as $designation)
                  {{$designation->norme}} <span class="fa fa-arrow-circle-right" aria-hidden="true"></span> {{$designation->name}} <br>
                @endforeach
              </td>


              {{-- <td>{{$nuance->designations->name}}</td> --}}
            </tr>
          @endforeach
        </tbody>
      </table>
    @endif
  </div>
@endsection

resources/views/nuances/nuancesShow.blade.php
@extends('template')

@section('title')
  Show nuance
@endsection

@section('content')
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header"> Fiche nuance
          </div>
          @if(Auth::check() and Auth::user()->admin)
            {{-- <p>Id :             {{ $nuance->id }}</p> --}}
          @endif
          <p>Nom :              {{ $nuance->nuanceName}}</p>
          <p>Famille :          {{ $nuance->famille}}</p>
          <p>Densité :          {{ $nuance->densite}}</p>
          <table>
            @foreach ($nuance->designations as $designation)
              <tr>
                <td class="col-sm-4">{{ $designation->designationNorme }}</td>
                <td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
                <td class="col-sm-4">{{ $designation->designationName }}</td>
              </tr>
            @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
  <a href="javascript:history.back()" class="btn bg-lightGrey"> <span class="fa fa-arrow-circle-left"> </span> Retour </a>
@endsection