routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::auth();
Auth::routes();

Route::any('/search', 'NuanceController@search');

Route::resource('user', 'UserController');

Route::resource('chute', 'ChuteController');
Route::resource('nuance', 'NuanceController');
Route::get('nuance/designation/{designation}', 'NuanceController@indexDesignation');
// Route::resource('designation', 'DesignationController');
Route::resource('commande', 'CommandeController');

app/Models/Chute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Chute extends Model
{
  // column allowed to be affected by create
  protected $fillable = [
    'CCPU', 'format', 'dimensions', 'poidsTheorique', 'poids reel', 'prixHorsTaxe'
  ];
  // une chute appartient à une nuance
  public function nuance()
  {
    return $this->belongsTo('App\Models\Nuance');
  }

}

app/Http/Controllers/ChuteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Repositories\ChuteRepository;

use App\Models\Chute;

class ChuteController extends Controller
{

  public function __construct(ChuteRepository $chuteRepository)
  {
    $this->chuteRepository = $chuteRepository;
  }

  public function index()
  {
    $chutes = $this->chuteRepository->getPaginate(25);
    $links = $chutes->render();
    return view('chutes.chutes', compact('chutes', 'links'));
  }

  public function create()
  {
    return view('chutes.chutesAdd');
  }

  public function store(Request $request)
  {

  }

  public function show($id)
  {

  }

  public function edit($id)
  {

  }

  public function update($id)
  {

  }

  public function destroy($id)
  {

  }
}
?>

resources/views/chutes/chutes.blade.php
@extends('template')

@section('title')
	Chutes
@endsection

@section('content')
	@if(Auth::check() and Auth::user()->admin)
		{!! link_to_route('chute.create', 'Ajouter une chute', [], ['class' => 'btn bg-lightGreen float-right']) !!}
	@endif

	@if (isset($info))
		<div class="row alert alert-info"> {{ $info }} </div>
	@endif

	<div class="mt-3 ml-5">
		{!! $links !!}
	</div>

	{{-- $table->increments('id');
	$table->timestamps();
	$table->integer('nuance_id')->unsigned(); //foreignKey
	$table->foreign('nuance_id')->references('id')->on('nuances')->onDelete('restrict')->onUpdate('restrict');
	$table->string('CCPU')->nullable();
	$table->enum('format', array('indifférent', 'rond', 'carre', '6Pans', 'tubes'))->default('indifférent');
	$table->string('diam')->nullable();
	$table->string('epaisseur')->nullable();
	$table->string('cote')->nullable();
	$table->string('longueurCoupe')->nullable();
	$table->string('poidsTheorique')->nullable(); // fill by controller dimensions*nuance->densite
	$table->float('poidsReel')->nullable();
	$table->float('prixHorsTaxe')->nullable(); --}}

	<div class="row">
		@foreach ($chutes as $chute)
			<div class="card col-sm-3">
				<div class="card-header bg-lightGrey">
					<a href="chute/{{$chute->id}}"> {{ $chute->id }}</a>
					<span class="float-right"> {{$chute->nuance->nuanceName}} </span>
				</div>
				<div class="card-body">
					<table>
						<tr>
							<td>Format: </td>
							<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
							<td> {{ $chute->format }} </td>
						</tr>
						@if (isset($chute->diam))
							<tr>
								<td>Diamètre: </td>
								<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
								<td> {{ $chute->diam }} </td>
							</tr>
						@endif
						@if (isset($chute->epaisseur))
							<tr>
								<td>Épaisseur: </td>
								<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
								<td> {{ $chute->epaisseur }} </td>
							</tr>
						@endif
						@if (isset($chute->cote))
							<tr>
								<td>Côté: </td>
								<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
								<td> {{ $chute->cote }} </td>
							</tr>
						@endif
						@if (isset($chute->longueurCoupe))
							<tr>
								<td>Longueur de coupe: </td>
								<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
								<td> {{ $chute->longueurCoupe }} </td>
							</tr>
						@endif
						<tr>
							<td>Poids: </td>
							<td class="col-sm-4"><span class="fa fa-arrow-circle-right" aria-hidden="true"></span></td>
							<td> {{ $chute->poidsTheorique }} </td>
						</tr>
					</table>
				</div>
			</div>
		@endforeach
	</div>
	{!! $links !!}
@endsection

resources/views/chutes/chutesAdd.blade.php
@extends('template')

@section('content')
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-10">
				<div class="card">
					<div class="card-header bg-lightGrey">
						Ajouter une chute
					</div>
					<div class="card-body">
						{!! Form::open(array('route' => 'chute.store', 'method' => 'POST')) !!}
						{{-- format --}}
						<div class="form-group row">
							{!! Form::label('format', 'Format:', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
							{!! Form::text('format', null, ['class' => 'col-md-8']) !!}
						</div>
					</div>
				</div>

			</div>

		</div>

	</div>



	{!! Form::open(array('route' => 'chute.store', 'method' => 'POST')) !!}
		<ul>
			<li>
				{!! Form::label('nuance_id', 'Nuance_id:') !!}
				{!! Form::text('nuance_id') !!}
			</li>
			<li>
				{!! Form::label('CCPU', 'CCPU:') !!}
				{!! Form::text('CCPU') !!}
			</li>
			<li>
				{!! Form::label('format', 'Format:') !!}
				{!! Form::text('format') !!}
			</li>
			<li>
				{!! Form::label('dimensions', 'Dimensions:') !!}
				{!! Form::text('dimensions') !!}
			</li>
			<li>
				{!! Form::label('poidsTheorique', 'PoidsTheorique:') !!}
				{!! Form::text('poidsTheorique') !!}
			</li>
			<li>
				{!! Form::label('poidsReel', 'PoidsReel:') !!}
				{!! Form::text('poidsReel') !!}
			</li>
			<li>
				{!! Form::label('prixHorsTaxe', 'PrixHorsTaxe:') !!}
				{!! Form::text('prixHorsTaxe') !!}
			</li>
			<li>
				{!! Form::submit() !!}
			</li>
		</ul>
	{!! Form::close() !!}
@endsection